/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class CounterJFrame extends javax.swing.JFrame {
int value = 0;
    /**
     * Creates new form CounterJFrame
     */
    public CounterJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panel1 = new java.awt.Panel();
        jProgressBar2 = new javax.swing.JProgressBar();
        counter1 = new colors.Counter();
        counter2 = new colors.Counter();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        javabutton = new javax.swing.JButton();
        phpbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 153, 153));

        jProgressBar2.setForeground(new java.awt.Color(51, 0, 153));
        jProgressBar2.setStringPainted(true);

        counter1.setBackground(new java.awt.Color(51, 0, 153));

        counter2.setBackground(new java.awt.Color(51, 0, 153));

        jLabel4.setFont(new java.awt.Font("Helvetica LT Std", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Score PHP");

        jLabel3.setFont(new java.awt.Font("Helvetica LT Std", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Score Java");

        javabutton.setText("vote");
        javabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javabuttonActionPerformed3(evt);
                javabuttonActionPerformed2(evt);
                javabuttonActionPerformed1(evt);
                javabuttonActionPerformed(evt);
            }
        });

        phpbutton.setText("vote");
        phpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phpbuttonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\materi\\SEMESTER 6\\RPLBK A\\TUGAS NETBEANS NARS\\javaicon.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\materi\\SEMESTER 6\\RPLBK A\\TUGAS NETBEANS NARS\\phpicon.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Kozuka Gothic Pro B", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Survey PHP vs JAVA");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("by: Nareswari Dyah Puspaningrum 21120117120002");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(phpbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(javabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(98, 98, 98)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(counter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(counter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel6))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel5)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(javabutton)
                            .addComponent(phpbutton))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(counter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(counter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void javabuttonActionPerformed3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javabuttonActionPerformed3
        counter1.increment();
        long nilaijava = counter1.getCount();
        long nilaiphp = counter2.getCount();
        //nilaiphp.setValue((int) counter1.getCount());
        //float nilaijava = Float.parseFloat(counter2.getvalue());

        float jumlah = nilaijava + nilaiphp;
        float bagi = (nilaiphp / jumlah);
        float persentase = bagi * 100;

        jProgressBar2.setValue((int) persentase);
    }//GEN-LAST:event_javabuttonActionPerformed3

    private void javabuttonActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javabuttonActionPerformed2

    }//GEN-LAST:event_javabuttonActionPerformed2

    private void javabuttonActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javabuttonActionPerformed1

    }//GEN-LAST:event_javabuttonActionPerformed1

    private void javabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javabuttonActionPerformed
//        counter1.increment();
//        long nilaijava = counter1.getCount();
//        long nilaiphp = counter2.getCount();
//        //nilaiphp.setValue((int) counter1.getCount());
//        //float nilaijava = Float.parseFloat(counter2.getvalue());
//
//        float jumlah = nilaijava + nilaiphp;
//        float bagi = (nilaiphp / jumlah);
//        float persentase = bagi * 100;
//
//        jProgressBar2.setValue((int) persentase);
//     //   jLabe1.setText(String.valueOf(persentase));
    }//GEN-LAST:event_javabuttonActionPerformed

    private void phpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phpbuttonActionPerformed
        counter2.increment();
        long nilaijava = counter1.getCount();
        long nilaiphp = counter2.getCount();
        //nilaiphp.setValue((int) counter1.getCount());
        //float nilaijava = Float.parseFloat(counter2.getvalue());

        float jumlah = nilaijava + nilaiphp;
        float bagi = (nilaiphp / jumlah);
        float persentase = bagi * 100;

        jProgressBar2.setValue((int) persentase);
      //  jLabe1.setText(String.valueOf(persentase));
    }//GEN-LAST:event_phpbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CounterJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private colors.Counter counter1;
    private colors.Counter counter2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JButton javabutton;
    private java.awt.Panel panel1;
    private javax.swing.JButton phpbutton;
    // End of variables declaration//GEN-END:variables
}
